name: Periodic health check

on:
  schedule:
    - cron: '0 18 * 4 5' #min hour dm m dw

jobs:
  health_check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check the deployed backend
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstack-part8-graphql.onrender.com/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 10s
          retry-all: false
      - name: Check the deployed frontend
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstack-part8-graphql-1.onrender.com/
          follow-redirect: false 
          max-attempts: 3
          retry-delay: 5s 
          retry-all: false
