name: Deployment pipeline

on:
  push:
    branches: [main]


jobs:
  deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install && cd graphql_server/ && npm install && cd ../graphql_frontend && npm install && cd ..
      - name: Check style
        run: cd graphql_server/ && npm run lint && cd ../graphql_frontend && npm run lint && cd ..
      - name: Build
        run: cd graphql_frontend && npm run build && cd ..
      - name: Unit test
        env: 
          MONGODB_URI: ${{secrets.MONGODB_URI}}
        run: cd graphql_server/ && npm run test && cd ../graphql_frontend && npm run test && cd ..
      - name: Install Playwright Browsers
        run:  npx playwright install --with-deps
      - name: Run Playwright tests
        env: 
          MONGODB_URI: ${{secrets.MONGODB_URI}}
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
